[package]
name = "lz-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lz-openapi = { path = "../lz-openapi" }
dioxus = { workspace = true, features = ["web", "router"] }
tracing = {workspace = true}
tracing-wasm = { workspace = true }

# Debug
log = { workspace = true }
dioxus-logger = { workspace = true }
console_error_panic_hook = { workspace = true }
