[package]
name = "lz-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lz-openapi = { path = "../lz-openapi" }
dioxus = { version = "0.5", features = ["web", "router"] }
tracing = {workspace = true}
tracing-wasm = {version = "0.2.1"}

# Debug
log = "0.4.19"
dioxus-logger = "0.4.1"
console_error_panic_hook = "0.1.7"
